/*
    The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
    Let us list the factors of the first seven triangle numbers:

    1: 1
    3: 1, 3
    6: 1, 2, 3, 6
    10: 1, 2, 5, 10
    15: 1, 3, 5, 15
    21: 1, 3, 7, 21
    28: 1, 2, 4, 7, 14, 28
    We can see that 28 is the first triangle number to have over five divisors.

    What is the value of the first triangle number to have over n divisors?
*/

function divisibleTriangleNumber(nbDivisors) {
    let i = 1;
    let maxDivisors = 0;
    let triangleValue = 0;
    while (maxDivisors < nbDivisors) {
        triangleValue = i * (i+1) / 2;
        maxDivisors = countNbDivisors(triangleValue);
        i++;
    }

    return triangleValue;
}

function countNbDivisors(n) {
    const primeFactorExponents = [];
    let prime = 2;
    let lastPrime = null;
    while (prime <=n ) {
        if (n % prime === 0) {
            n /= prime;
            if (prime === lastPrime) {
                primeFactorExponents[primeFactorExponents.length-1]++;
            } else {
                primeFactorExponents[primeFactorExponents.length] = 2;
                lastPrime = prime;
            }
        } else {
            prime++;
        }
    }
    return primeFactorExponents.length !== 0? primeFactorExponents.reduce((a, b)=>a*b) : 1;
}

console.log(divisibleTriangleNumber(1));
